version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    container_name: my-db
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=strongpasswd
      - MYSQL_ROOT_PASSWORD=passwd
      - TZ="Asia/Tokyo"
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -ppasswd
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      external-api:
        ipv4_address: 172.18.0.5
      internal-db:

    

  app:
    build: ./python
    container_name: app-python
    ports:
      - 5050:5000
    networks:
      external-api:
      internal-db:
    depends_on:
      db:
        condition: service_healthy


networks:
  external-api:
    external: true
    
  internal-db:
